---
- name: Configuration automation controller
  hosts: localhost
  become: false
  gather_facts: false
  pre_tasks:
    - name: include vars 
      ansible.builtin.include_vars:
        dir: ./yaml
        ignore_files: [controller_config_yml.template]
  roles:
    - infra.controller_configuration.dispatch
