---
- name: Configuration automation controller
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    
    # Using the Tower env names for backwards compatibility
    controller_hostname: "{{ lookup('ansible.builtin.env', 'TOWER_HOST') }}"
    controller_username: "{{ lookup('ansible.builtin.env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('ansible.builtin.env', 'TOWER_PASSWORD') }}"
    controller_validate_certs: "{{ lookup('ansible.builtin.env', 'TOWER_VERIFY_SSL') | default(false) }}"
  tasks:
    - name: include vars 
      ansible.builtin.include_vars:
        dir:  ./yaml
        ignore_files: [controller_config_yml.template]
        extensions:
          - ['yml']
    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
  # roles:
  #  - {role: infra.controller_configuration.organizations, when: controller_organizations is defined}
  
  # tasks:
  #   - name: include variable
  #     ansible.builtin.include_vars:
  #       file: vars_ctrl_content_org_create.yml