---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    
    # Using the Tower env names for backwards compatibility
    controller_hostname: "{{ lookup('ansible.builtin.env', 'TOWER_HOST') }}"
    controller_username: "{{ lookup('ansible.builtin.env', 'TOWER_USERNAME') }}"
    controller_password: "{{ lookup('ansible.builtin.env', 'TOWER_PASSWORD') }}"
    controller_validate_certs: "{{ lookup('ansible.builtin.env', 'TOWER_VERIFY_SSL') | default(false) }}"
  tasks:
    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: ./yaml
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
      tags:
        - always

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
...
